### ISSUE TITLE
ROS Humble Migration

### ISSUE THREAD

**Issue by gezp** [robomaster-oss/rmoss_core#22]
#### Feature description
当前项目依赖的ROS版本为Galactic，迁移依赖至ROS最新版本Humble，以获得新的ROS特性，以及性能提升。

#### Implementation considerations

实现步骤：
- 采用ros版本号作为分支号，将当前主分支main改名为galactic.
- 创建新分支humble.
- 将humble分支设为默认分支.

完成情况：

核心功能项目：
- [x] [rmoss_interfaces](https://github.com/robomaster-oss/rmoss_interfaces) PR: https://github.com/robomaster-oss/rmoss_interfaces/pull/2
- [x] [rmoss_core](https://github.com/robomaster-oss/rmoss_core) PR: https://github.com/robomaster-oss/rmoss_core/pull/28
- [x] [rmoss_contrib](https://github.com/robomaster-oss/rmoss_contrib) PR: https://github.com/robomaster-oss/rmoss_contrib/pull/12
- [x] [rmoss_gazebo](https://github.com/robomaster-oss/rmoss_gazebo) PR: https://github.com/robomaster-oss/rmoss_gazebo/pull/7
- [x] [rmoss_gz_resources](https://github.com/robomaster-oss/rmoss_gz_resources) PR: https://github.com/robomaster-oss/rmoss_gz_resources/pull/1

仿真项目：
- [x] [rmua19_gazebo_simulator](https://github.com/robomaster-oss/rmua19_gazebo_simulator) PR: https://github.com/robomaster-oss/rmua19_gazebo_simulator/pull/16

其它项目：
- [ ] ~[rmoss_daheng_driver](https://github.com/robomaster-oss/rmoss_daheng_driver)~
- [x] [rmoss_mindvision_driver](https://github.com/robomaster-oss/rmoss_mindvision_driver)

**Comment by Ericsii** [comment]
70caf905e851f6f7d245ec327dd6bdc8bfef6167

**Comment by Ericsii** [comment]
rmoss_mindvision_driver迁移完成，请重新设置一下仓库默认分支

**Comment by gezp** [comment]
done
