### ISSUE TITLE
Support image_transport for CamServer

### ISSUE THREAD

**Issue by Ericsii** [robomaster-oss/rmoss_core#29]
#### Feature description
当前项目中`rmoss_cam`的实现没有没有基于[image_transport](https://github.com/ros-perception/image_common)，因此无法直接对于JPG/PNG等图像压缩或视频流的message传输提供支持。基于[image_transport](https://github.com/ros-perception/image_common)来实现`cam`节点能直接使用[image_transport_plugins](https://github.com/ros-perception/image_transport_plugins)中提供的各种压缩格式传输图像，满足不同带宽或不同使用场景的需求。

#### Implementation considerations

如需基于image_transport来实现rmoss_cam，可能需要对目前已有的 cam_server 和 cam_client 部分重新设计

**Comment by gezp** [comment]
目前的rmoss_cam的实现方案略显复杂，需要重新设计一下，对于压缩图像传输的支持，目前有两种可行方案的考虑：
* （1）将基于`image_transport`传输的方案集成到`CamServer`和`CamClient`中，发布`xxx/image/compressed`topic, 可以通过ros parameter决定是否使用压缩方式。
* （2）实现新的`CompressedCamServer`和`CompressedCamClient` （分别继承CamServer和CamClient），不过这里的CamServer和CamClient中需要设计相应interface，这样就可以提供继承方式提高代码的复用。

你看有什么想法没？ @Ericsii

**Comment by Ericsii** [comment]
我倾向选(1)第一种方式，将`image_transport`集成到已有的`CamServer`和`CamClient`里面。

本身`image_transport`就是针对与图像传输的官方推荐实现方式。如果使用(2)的方式来实现意味着将会有两种型式的`CamServer`和`CamClient`，可能会对使用者造成误导从而优先使用了不被官方推荐的无`image_transport`的方式来调用相机。

**Comment by gezp** [comment]
> 我倾向选(1)第一种方式

可以的，我觉得没问题，你看有没有空尝试实现一下？ @Ericsii

**Comment by Ericsii** [comment]
可以的

**Comment by gezp** [comment]
Done
