### ISSUE TITLE
I wonder why the default databits is 8

### ISSUE THREAD

**Issue by ggamaz** [robomaster-oss/rmoss_core#33]
![error](https://user-images.githubusercontent.com/103712346/225631910-e8255e9d-e679-4f1c-b34d-a45aab226fbf.png)

**Comment by ggamaz** [comment]
I am new to this, just curious about it

**Comment by ggamaz** [comment]
sorry,the default is 0

**Comment by gezp** [comment]
it seems a bug, 0 is a invalid databits.
https://github.com/robomaster-oss/rmoss_core/blob/94ff4612500f856af62b2b40029bf9937971abe8/rmoss_base/src/transporter_driver/uart_transporter.cpp#L65-L84

**Comment by gezp** [comment]
done
