### ISSUE TITLE
Add camera_info topic to `rmoss_cam`

### ISSUE THREAD

**Issue by Ericsii** [robomaster-oss/rmoss_core#36]
#### Feature description
可以考虑在`rmoss_cam`中加入`sensor_msgs::cameraInfo`消息的topic

#### Implementation considerations
- 使用`image_transport`中的`camearaPublisher`同时发布`camera_info`和`image_raw`
- 使用原生`rclcpp::Publisher`单独发布`camera_info`

**Comment by gezp** [comment]
想问一下，这么做的应用场景有哪些？camera_info有必要和image同频率发布吗？

**Comment by Ericsii** [comment]
已改用分离的publisher来发布camera_info信息。加入这个publisher是为了兼容其他大部分的ros开源项目。

**Comment by gezp** [comment]
因为rmoss_cam中的`CamServer`是设计和`CamClient`搭配使用的，就像`CameraPublisher`和`CameraSubscriber`搭配使用一样。当然为了提高兼容性确实是一个考虑的点，我觉得可以加一个bool参数`use_image_transport_camera_publisher`来确定是使用原始的模式，还是使用`CameraPublisher`模式来兼容其他模块。

**Comment by Ericsii** [comment]
好的，这种形式应该可以。我改一下这个PR

**Comment by Ericsii** [comment]
@gezp 已经修改PR

**Comment by gezp** [comment]
done
